
name: dc-testsuite-kob
services:
  kob-testsuite:
    build:
      context: .
    container_name: kob-testsuite
    environment:
      - MAVEN_OPTS=-Dcucumber.filter.tags=${TESTSUITE_TESTS}
      - KOB_STARTBROWSER=false
    ports:
      - "9010:9010"
      - "9011:9011"
      - "443:443"
    volumes:
      - ./tiger.yaml:/app/tiger.yaml:ro
      - ./kob.yaml:/app/kob.yaml:ro
      - ./diga.yaml:/app/diga.yaml:ro
      - ./activateResponse.xml:/app/activateResponse.xml:ro
      - ./createResponse.xml:/app/createResponse.xml:ro
      - ./settings.xml:/root/.m2/settings.xml:ro
      - kob-testsuite-maven:/.m2/repository:rw
      - ./report:/app/report:rw
  vauServer:
    image: gematik1/erp-vau-proxy-server
    environment:
      - ENCRYPTION_SERVICE_URL=http://vauCryptoServer:8080
      - TARGET_URL=http://kob-testsuite:8080
  vauCryptoServer:
    image: gematik1/erp-vau-crypto-service

volumes:
  kob-testsuite-maven:
    name: kob-testsuite-maven
  kob-testsuite-report:
    name: kob-testsuite-report
