
name: dc-testsuite-kob
services:
  kob-testsuite:
    image: gematik1/kob-testsuite:1.0.6
    container_name: kob-testsuite
    environment:
      - MAVEN_OPTS=-Dcucumber.filter.tags=${TESTSUITE_TESTS}
      - KOB_STARTBROWSER=false
      - KOB_PSURL=http://host.docker.internal:8080  # URL to connect PS with test driver interface if available
      - KOB_ASURL=https://host.docker.internal:8443 # ULR to connect ePA mock services to run tests, e.g. vau handshake test
    ports:
      - "${KOB_WORKFLOW_UI_EXPOSE_PORT:-9010}:9010"
      - "${KOB_TIGER_ADMIN_EXPOSE_PORT:-9011}:9011"
      - "${KOB_TIGER_PROXY_EXPOSE_PORT:-443}:443"
    volumes:
      - ./tiger.yaml:/app/tiger.yaml:ro
      - ./kob.yaml:/app/kob.yaml:ro
      - ./settings.xml:/home/kobtest/.m2/settings.xml:ro
      - kob-testsuite-maven:/home/kobtest/.m2/repository/:rw
      - kob-testsuite-report:/app/report/:rw

volumes:
  kob-testsuite-maven:
    name: kob-testsuite-maven
  kob-testsuite-report:
    name: kob-testsuite-report
