
name: dc-testsuite-kob
services:
  kob-testsuite:
    image: gematik1/kob-testsuite:0.6.4
    container_name: kob-testsuite
    environment:
      - MAVEN_OPTS=-Dcucumber.filter.tags=${TESTSUITE_TESTS}
      - KOB_STARTBROWSER=false
      - KOB_PSURL=http://host.docker.internal:8080  # URL to connect PS with test driver interface if available
      - KOB_ASURL=https://host.docker.internal:8443 # ULR to connect ePA mock services to run tests, e.g. vau handshake test
    ports:
      - "9010:9010"
      - "9011:9011"
      - "443:443"
    volumes:
      - ./tiger.yaml:/app/tiger.yaml
      - ./kob.yaml:/app/kob.yaml
      - ./ca.p12:/app/ca.p12
      - kob-testsuite-maven:/.m2
      # has to be 'copied' AFTER the volume is mounted
      - ./settings.xml:/.m2/settings.xml
volumes:
  kob-testsuite-maven:
    name: kob-testsuite-maven
