
name: dc-testsuite-kob
services:
  kob-testsuite:
    build:
      context: .
    container_name: kob-testsuite
    environment:
      - MAVEN_OPTS=-Dcucumber.filter.tags=${TESTSUITE_TESTS}
      - KOB_STARTBROWSER=false
    ports:
      - "${KOB_WORKFLOW_UI_EXPOSE_PORT:-9010}:9010"
      - "${KOB_TIGER_ADMIN_EXPOSE_PORT:-9011}:9011"
      - "${KOB_TIGER_PROXY_EXPOSE_PORT:-443}:443"
    volumes:
      - ./tiger.yaml:/app/tiger.yaml:ro
      - ./kob.yaml:/app/kob.yaml:ro
      - ./diga.yaml:/app/diga.yaml:ro
      - ./activateResponse.xml:/app/activateResponse.xml:ro
      - ./createResponse.xml:/app/createResponse.xml:ro
      - ./settings.xml:/root/.m2/settings.xml:ro
      - kob-testsuite-maven:/.m2/repository:rw
      - ./report:/app/report:rw
  vauServer:
    image: gematik1/erp-vau-proxy-server
    environment:
      - ENCRYPTION_SERVICE_URL=http://vauCryptoServer:8080
      - TARGET_URL=${VAU_SERVER_TARGET_URL}
  vauCryptoServer:
    image: gematik1/erp-vau-crypto-service
  vauTranslationClient:
    image: gematik1/erp-vau-proxy-client:1.0.29
    environment:
      - FORWARD_TARGET_URL=https://erp-dev.zentral.erp.splitdns.ti-dienste.de
    extra_hosts:
      - ${VAU_TRANSLATION_CLIENT_ERP_DEV_HOST:-erp-dev.zentral.erp.splitdns.ti-dienste.de}:10.31.194.12
      - ${VAU_TRANSLATION_CLIENT_ERP_REF_HOST:-erp-ref.zentral.erp.splitdns.ti-dienste.de}:10.31.195.10


volumes:
  kob-testsuite-maven:
    name: kob-testsuite-maven
  kob-testsuite-report:
    name: kob-testsuite-report
